---
- name: Deploy website files only (Apache already installed by Terraform)
  hosts: webservers
  become: true

  vars:
    web_root: /var/www/html
    workspace_env: "{{ lookup('env', 'WORKSPACE') | default('', true) }}"
    app_src_fallback: >-
      {{
        (workspace_env | length > 0)
        | ternary(workspace_env ~ '/app', playbook_dir ~ '/../app')
      }}
    app_src_final: "{{ app_src | default(app_src_fallback, true) }}"

  tasks:
    - name: Validate app source exists on Jenkins (controller)
      delegate_to: localhost
      become: false
      run_once: true
      stat:
        path: "{{ app_src_final }}"
      register: app_src_stat

    - name: Stop if app source path is invalid
      delegate_to: localhost
      become: false
      run_once: true
      fail:
        msg: "Source folder not found: {{ app_src_final }}. Jenkins should clone app into WORKSPACE/app or pass -e app_src=..."
      when: not app_src_stat.stat.exists

    - name: Ensure web root exists
      file:
        path: "{{ web_root }}"
        state: directory
        owner: www-data
        group: www-data
        mode: "0755"

    - name: Copy website files to Apache web root
      copy:
        src: "{{ app_src_final }}/"
        dest: "{{ web_root }}/"
        owner: www-data
        group: www-data
        mode: "0644"
      notify: Reload Apache

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded
