---
- name: Deploy static website with directory listing (override index)
  hosts: webservers
  become: true

  vars:
    web_root: /var/www/html

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Ensure Apache is running and enabled
      service:
        name: apache2
        state: started
        enabled: yes

    # Make Apache show directory listing (Indexes)
    # And override index.html by disabling DirectoryIndex
    - name: Configure Apache directory listing for web root
      copy:
        dest: /etc/apache2/conf-available/dir-listing.conf
        content: |
          <Directory {{ web_root }}>
              Options +Indexes
              AllowOverride None
              Require all granted
              DirectoryIndex disabled
          </Directory>
      notify: Reload Apache

    - name: Enable directory listing config
      command: a2enconf dir-listing
      args:
        creates: /etc/apache2/conf-enabled/dir-listing.conf
      notify: Reload Apache

    # Validate Jenkins passed app_src correctly
    - name: Fail if app_src is not provided or path does not exist on controller
      delegate_to: localhost
      become: false
      stat:
        path: "{{ app_src }}"
      register: app_src_stat

    - name: Stop if app_src is invalid
      delegate_to: localhost
      become: false
      fail:
        msg: "app_src '{{ app_src }}' not found on controller. Jenkins must pass -e app_src=${WORKSPACE}/app"
      when: not app_src_stat.stat.exists

    - name: Ensure web root exists
      file:
        path: "{{ web_root }}"
        state: directory
        owner: www-data
        group: www-data
        mode: "0755"

    - name: Deploy website files from CI workspace to web servers
      copy:
        src: "{{ app_src }}/"
        dest: "{{ web_root }}/"
        owner: www-data
        group: www-data
        mode: "0644"

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded
