---
- name: Deploy static website to web servers
  hosts: webservers
  become: yes

  vars:
    # Jenkins passes this: -e APP_SRC_DIR=${WORKSPACE}
    # Fallback for local testing: current directory
    APP_SRC_DIR: "{{ APP_SRC_DIR | default(playbook_dir) }}"

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Apache
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Ensure Apache is enabled and running
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes

    - name: Ensure web root exists
      ansible.builtin.file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Copy HTML/CSS/JS files from app repo workspace
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0644'
      with_fileglob:
        - "{{ APP_SRC_DIR }}/*.html"
        - "{{ APP_SRC_DIR }}/*.css"
        - "{{ APP_SRC_DIR }}/*.js"
      notify: Reload Apache

    - name: Copy image files from app repo workspace
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0644'
      with_fileglob:
        - "{{ APP_SRC_DIR }}/*.jpg"
        - "{{ APP_SRC_DIR }}/*.jpeg"
        - "{{ APP_SRC_DIR }}/*.png"
        - "{{ APP_SRC_DIR }}/*.gif"
        - "{{ APP_SRC_DIR }}/*.svg"
        - "{{ APP_SRC_DIR }}/*.webp"
      notify: Reload Apache

    # Optional: Verify remote index.html content (helps confirm deploy)
    - name: Show remote index.html checksum
      ansible.builtin.shell: "sha256sum /var/www/html/index.html | awk '{print $1}'"
      register: remote_index_checksum
      changed_when: false

    - name: Print remote checksum
      ansible.builtin.debug:
        msg: "REMOTE index.html checksum: {{ remote_index_checksum.stdout }}"

  handlers:
    - name: Reload Apache
      ansible.builtin.service:
        name: apache2
        state: reloaded
