---
- name: Deploy static website to web servers
  hosts: webservers
  become: yes

  vars:
    app_src_dir: "{{ lookup('env', 'WORKSPACE') | default(playbook_dir, true) }}"

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Apache
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Ensure Apache is enabled and running
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes

    - name: Remove default Apache index.html
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent

    - name: Copy website files from Jenkins workspace
      ansible.builtin.copy:
        src: "{{ app_src_dir }}/"
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0755'
      notify: Reload Apache

  handlers:
    - name: Reload Apache
      ansible.builtin.service:
        name: apache2
        state: reloaded
