---
- name: Deploy static website to web servers
  hosts: webservers
  become: yes

  vars:
    app_src_dir: "{{ lookup('env', 'WORKSPACE') }}/app"

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Remove Apache default page
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Deploy site from Git repo
      copy:
        src: "{{ app_src_dir }}/"
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0755'
      notify: Reload Apache

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded
